
addons:
  postgresql: "9.3"

before_script:
  - mysql -e 'create database run_after_commit;'
  - psql -c 'create database run_after_commit;' -U postgres

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

install:
  - "travis_retry bundle install"

script: "bundle exec rake test"
sudo: false

